name: CO_Staff
version: '1.0-SNAPSHOT'
main: it.craftopoly.co_staff.CO_Staff
api-version: 1.20
commands:
  vanish:
    aliases: []
  chat:
    aliases: [ c ]
  teleport:
    aliases: [ tp ]
  mute:
    aliases: [ ]
  ban:
    aliases: [ ]
  unmute:
    aliases: [ ]
  unban:
    aliases: [ ]
